apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kdc.fullname" . }}
  labels:
    {{- include "kdc.labels" . | nindent 4 }}
data:
  kadm5.acl: |
    */admin@{{ .Values.realm }} *
    {{- range $index0 := until (sub (.Values.replicaCount | int) 1 | int) }}
    kiprop/kdc-{{ add1 $index0 }}.kdc.{{ $.Release.Namespace }}.{{ $.Values.clusterDomain }}{{ $.Values.realm }} p
    {{- end }}

  kpropd.acl: |
    host/kdc-0.kdc.{{ .Release.Namespace }}.{{ .Values.clusterDomain }}@{{ .Values.realm }}

  kdc.conf: |
    [realms]
      {{ .Values.realm }} = {
        acl_file                = /etc/krb5kdc/kadm5.acl
        database_name           = /var/lib/krb5kdc/principal
        key_stash_file          = /var/lib/krb5kdc/stash
        kadmind_port            = 749
        kdc_ports               = 88
        iprop_enable            = true
        iprop_port              = 2121
        max_life                = 10h 0m 0s
        max_renewable_life      = 7d 0h 0m 0s
        master_key_type         = aes256-cts-hmac-sha1-96
        supported_enctypes      = aes256-cts-hmac-sha1-96
        default_principal_flags = +preauth
      }

  krb5.conf: |
    [libdefaults]
      default_realm = {{ .Values.realm }}
      kdc_timesync  = 1
      ccache_type   = 4
      forwardable   = true
      proxiable     = true

    [realms]
      {{ .Values.realm }} = {
        {{- range $index0 := until (.Values.replicaCount | int) }}
        kdc = kdc-{{ $index0 }}.kdc.{{ $.Release.Namespace }}.{{ $.Values.clusterDomain }}
        {{- end }}
        admin_server = kdc-0.kdc.{{ .Release.Namespace }}.{{ .Values.clusterDomain }}
      }

    [domain_realm]
      .{{ .Values.domain }} = {{ .Values.realm }}
      {{ .Values.domain }} = {{ .Values.realm }}
