apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kdc.fullname" . }}
  labels:
    {{- include "kdc.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kdc.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kdc.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "kdc.fullname" . }}
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kdc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kdc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kdc.fullname" . }}
      initContainers:
        - name: init-volumes
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add:
                - DAC_OVERRIDE
                - FOWNER
                - CHOWN
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/init-volumes
          volumeMounts:
            - name: {{ include "kdc.fullname" . }}
              mountPath: /var/lib/krb5kdc
        - name: init-realm
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/init-realm
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/krb5kdc
              readOnly: true
            - name: {{ include "kdc.fullname" . }}
              mountPath: /var/lib/krb5kdc
      containers:
        - name: kadmind-kpropd
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/exec-kadmind-kpropd
          ports:
            - name: kerberos-tcp
              containerPort: 88
              protocol: TCP
            - name: kerberos-udp
              containerPort: 88
              protocol: UDP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: {{ include "kdc.fullname" . }}
              mountPath: /var/lib/krb5kdc
            - name: config
              mountPath: /etc/krb5kdc
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: krb5kdc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/exec-krb5kdc
          env:
            {{- toYaml .Values.env | nindent 12 }}
          ports:
            - name: kerberos-tcp
              containerPort: 88
              protocol: TCP
            - name: kerberos-udp
              containerPort: 88
              protocol: UDP
          volumeMounts:
            - name: {{ include "kdc.fullname" . }}
              mountPath: /var/lib/krb5kdc
            - name: config
              mountPath: /etc/krb5kdc
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
